## Numpy: Arrays filtern

In dieser Lektion lernst du:

- Wie du `Numpy` - Arrays filtern kannst

In [10]:
import numpy as np

In [12]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [14]:
b = np.array([False, True, True, False])
print(b)

[False  True  True False]


Mithilfe der `[ ]-Schreibweise`, die du schon vom _Zugriff auf Listen_ und vom _list slicing_ her kennst, können wir ein Numpy-Array einem anderen Numpy-Array übergeben, das dann gefiltert wird:

In [21]:
a[b]
#filtere array a nach b (gib nur die Positionen zurück die ein True enthalten quasi: 2 und 3 also)

array([2, 3])

In [23]:
a

array([1, 2, 3, 4])

In [25]:
a >=3

array([False, False,  True,  True])

In [27]:
a [a>=3]

array([3, 4])

In [33]:
#oder sauberer so:
c = a>=3
print(c)
print(a[c])

[False False  True  True]
[3 4]


In [35]:
print (a [a>=3])

[3 4]
