## Numpy: Mehrdimensionale Arrays

In Numpy kannst du auch mit **mehrdimensionalen Arrays** (**Matrizen**) arbeiten.

In [5]:
import numpy as np

In [7]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(a)

[1 2 3 4 5 6 7 8]


In [11]:
a.reshape((2, 4))
#mach mein array mehrdimensional: 2 rows, 4 cols

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
print(a)

[1 2 3 4 5 6 7 8]


In [21]:
reshaped= a.reshape((2, 4))

print(reshaped)
print(reshaped[0])
print(reshaped[1])

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]
[5 6 7 8]


In [23]:
print(reshaped[0][3])

4


### Parameter-Platzhalter: Anzahl von Einträgen in einer Dimension offen lassen

In [30]:
a.reshape((-1, 4)) #soll vie spalten haben, zeilen weiß ich  nicht
#hier macht er natürlich  2 weil es nur 8 eintraege hat insgesamt

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
a.reshape(( 4, -1))#soll 4 zeilen haben, spalten weiß ich nicht

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### Aus mehrdimensionalem Array ein eindimensionales erzeugen

In [45]:
b= np.array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
b

array([[1, 2, 3],
       [4, 5, 6]])

#### eindimensional machen

In [52]:
b.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [54]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
b.reshape(-1)#so gehts auch(einfacher wenn du anzahl nicht weißt)

array([1, 2, 3, 4, 5, 6])

In [60]:
b.shape #gibt dimensionen meines Array an

(2, 3)

In [72]:
c= np.array([1, 2, 3, 4, 5])
c.reshape((4, 2)) # unmöglich draus ein vierzeiliges zweispaltiges array zu shapen!

ValueError: cannot reshape array of size 5 into shape (4,2)

In [74]:
c= np.array([1, 2, 3, 4, 5, 6, 7, 8])
c.reshape((4, 2)) # so klappts!

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])