# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [9]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3, 4])


# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([
[1, 2, 3, 4],
[5, 6, 7, 8]]
)


# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8]],
    [[1, 2, 3, 4],
     [5, 6, 7, 8]],
    [[1, 2, 3, 4],
     [5, 6, 7, 8]]]
             )
a1.ndim, a2.ndim, a3.ndim


(1, 2, 3)

In [10]:
#Now we've you've created 3 different arrays, let's find details about them.
a1.ndim, a2.ndim, a3.ndim
a1.shape, a2.shape, a3.shape
type(a1)
#Find the shape, number of dimensions, data type, size and type of each array.

numpy.ndarray

In [12]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.ndim, a1.shape, a1.dtype, a1.size, type(a1)

(1, (4,), dtype('int32'), 4, numpy.ndarray)

In [13]:
# Attributes of 2-dimensional array
a2.ndim, a2.shape, a2.dtype, a2.size, type(a2)

(2, (2, 4), dtype('int32'), 8, numpy.ndarray)

In [14]:
# Attributes of 3-dimensional array
a3.ndim, a3.shape, a3.dtype, a3.size, type(a3)

(3, (3, 2, 4), dtype('int32'), 24, numpy.ndarray)

In [17]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [19]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [21]:
# Create an array within a range of 0 and 100 with step 3
array_range = np.arange(0, 100, 3)
array_range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [47]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array =  np.random.randint(0, 10, (7, 2))
random_array

array([[9, 1],
       [9, 3],
       [7, 6],
       [8, 7],
       [4, 1],
       [4, 7],
       [9, 8]])

In [26]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_2 = np.random.random((3, 5))
random_array_2

array([[0.85591624, 0.17363948, 0.16223061, 0.64070167, 0.48893886],
       [0.4605907 , 0.02705367, 0.1587909 , 0.83068447, 0.68313257],
       [0.13044963, 0.8476688 , 0.69069923, 0.82898308, 0.63351372]])

In [32]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_3 =  np.random.randint(0, 10, (4, 6))
random_array_3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [33]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_var =  np.random.randint(1, 10, (3, 7))
random_array_var

# Find the unique numbers in the array you just created
# random_array_var

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [37]:
random_array_var.ndim

2

In [35]:
np.unique(random_array_var)

array([1, 2, 3, 4, 5, 7, 9])

In [38]:
# Find the 0'th index of the latest array you created
random_array_var[0][0]

9

In [44]:
# Get the first 2 rows of latest array you created
random_array_var[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [45]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_var[:2,:2]

array([[9, 1],
       [5, 3]])

In [51]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array_new =  np.random.randint(0, 10, (3, 5))
ones_new = np.ones((3, 5))
random_array_new

array([[2, 6, 0, 3, 3],
       [4, 6, 6, 3, 6],
       [2, 5, 1, 9, 8]])

In [54]:
# Add the two arrays together
ones_new + random_array_new

array([[ 3.,  7.,  1.,  4.,  4.],
       [ 5.,  7.,  7.,  4.,  7.],
       [ 3.,  6.,  2., 10.,  9.]])

In [55]:
# Create another array of ones of shape (5, 3)
ones_more_new = np.ones((5, 3))
ones_more_new

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [68]:
# Try add the array of ones and the other most recent array together
latest_array = ones_new.T + ones_more_new

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [59]:
# Create another array of ones of shape (3, 5)
ones_again = np.ones((3, 5))
ones_again

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
# Subtract the new array of ones from the other most recent array
ones_again - ones_more_new.T

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [63]:
# Multiply the ones array with the latest array
ones_again * ones_more_new.T

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
# Take the latest array to the power of 2 using '**'
latest_array ** 2

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [69]:
# Do the same thing with np.square()
np.square(latest_array)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [70]:
# Find the mean of the latest array using np.mean()
np.mean(latest_array)

2.0

In [71]:
# Find the maximum of the latest array using np.max()
np.max(latest_array)

2.0

In [72]:
# Find the minimum of the latest array using np.min()
np.min(latest_array)

2.0

In [73]:
# Find the standard deviation of the latest array
np.std(latest_array)

0.0

In [74]:
# Find the variance of the latest array
np.var(latest_array)

0.0

In [75]:
latest_array

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [77]:
# Reshape the latest array to (3, 5, 1)
latest_array = latest_array.reshape(3, 5, 1)
latest_array

array([[[2.],
        [2.],
        [2.],
        [2.],
        [2.]],

       [[2.],
        [2.],
        [2.],
        [2.],
        [2.]],

       [[2.],
        [2.],
        [2.],
        [2.],
        [2.]]])

In [78]:
# Transpose the latest array
latest_array.T

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

What does the transpose do?

It turns it to shape (1, 5, 3)

In [79]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_array_one =  np.random.randint(0, 10, (3, 3))
random_array_two =  np.random.randint(0, 10, (3, 2))


In [80]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array_one, random_array_two)

array([[ 53,  90],
       [106, 168],
       [ 48,  48]])

In [81]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_array_three =  np.random.randint(0, 10, (4, 3))
random_array_four =  np.random.randint(0, 10, (4, 3))

In [82]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array_three, random_array_four)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [83]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(random_array_three, random_array_four.T)

array([[72, 65, 42, 49],
       [18, 14, 16,  0],
       [45, 74, 38, 49],
       [27, 72, 26, 56]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [84]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
random_array_five =  np.random.randint(0, 10, (4, 3))
random_array_six =  np.random.randint(0, 10, (4, 3))

In [100]:
random_array_six

array([[5, 6, 3],
       [6, 7, 0],
       [5, 7, 4],
       [3, 1, 5]])

In [99]:
random_array_five

array([[0, 1, 1],
       [5, 6, 4],
       [0, 0, 2],
       [1, 4, 9]])

In [88]:
# Compare the two arrays with '>'
random_array_six > random_array_five

array([[ True,  True,  True],
       [ True,  True, False],
       [ True,  True,  True],
       [ True, False, False]])

What happens when you compare the arrays with `>`?

In [89]:
# Compare the two arrays with '>='
random_array_six >= random_array_five

array([[ True,  True,  True],
       [ True,  True, False],
       [ True,  True,  True],
       [ True, False, False]])

In [91]:
# Find which elements of the first array are greater than 7
random_array_five > 7

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True]])

In [92]:
# Which parts of each array are equal? (try using '==')
random_array_five == random_array_six

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [93]:
# Sort one of the arrays you just created in ascending order
np.sort(random_array_five)

array([[0, 1, 1],
       [4, 5, 6],
       [0, 0, 2],
       [1, 4, 9]])

In [96]:
random_array_five

array([[0, 1, 1],
       [5, 6, 4],
       [0, 0, 2],
       [1, 4, 9]])

In [101]:
random_array_six

array([[5, 6, 3],
       [6, 7, 0],
       [5, 7, 4],
       [3, 1, 5]])

In [98]:
# Sort the indexes of one of the arrays you just created
np.argsort(random_array_six)

array([[2, 0, 1],
       [2, 0, 1],
       [2, 0, 1],
       [1, 0, 2]], dtype=int64)

## For the first row [5, 6, 3], sorting it gives [3, 5, 6]. The indices of the sorted elements are [2, 0, 1].

In [104]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(random_array_five)

11

In [105]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random_array_five)

0

In [107]:
random_array_five

array([[0, 1, 1],
       [5, 6, 4],
       [0, 0, 2],
       [1, 4, 9]])

In [106]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(random_array_five, axis=1) #spaltenweiser Vergleich welche zahl die höchste

array([1, 1, 2, 2], dtype=int64)

In [108]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(random_array_five, axis=0)

array([0, 2, 0], dtype=int64)

In [49]:
# Create an array of normally distributed random numbers


In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.